name: KairosCollaborative
favicon: null
layout_spectrum: 0.5287652439437807
typography_spectrum: 0.5484268220607191
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.3675704556517303
  lightness: 0.14221017574891448
  saturation: 0.6952192869503051
  rhythmicContrast: 0.8938004332594573
purpose: []
